<a href="https://colab.research.google.com/github/sarnesh444/git-github/blob/firstbranch/pandasduplicateelimination.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd

In [0]:
cocubes=pd.read_csv("CoCubesPreassess Scores.xlsx")

In [0]:
cocubes.head()

   CoCubesId                          Name  ...  Software Engineer Software Tester
0    2793828                Rohith Narayan  ...         Good to go      Good to go
1    2793400              Sunkavalli Jnani  ...         Good to go      Good to go
2    2792958       Krishna Vivek Vinnakota  ...         Good to go      Good to go
3    2793375                      P Anusha  ...         Good to go      Good to go
4    2794244  Chilukala Sai Giridhar Reddy  ...         Good to go      Good to go

[5 rows x 26 columns]

In [0]:
cocubes.iloc[0][2]

1210416751

In [0]:
unplaced=pd.read_excel("Unplaced Students 10102019.xlsx")

In [0]:
unplaced.head()

   Unnamed: 0                    Unnamed: 1  ...       Unnamed: 20      Unnamed: 21
0         NaN  Student Details - 2020 Batch  ...               NaN              NaN
1         NaN                           NaN  ...               NaN              NaN
2         NaN                           NaN  ...               NaN              NaN
3         NaN                    CoCubes Id  ...  Graduation Marks  Graduation Year
4         NaN                       2792845  ...               7.3             2020

[5 rows x 22 columns]

In [0]:
unplaced1=unplaced.drop(unplaced.index[0])

In [0]:
unplaced1.head()

   Unnamed: 0  Unnamed: 1  ...       Unnamed: 20      Unnamed: 21
1         NaN         NaN  ...               NaN              NaN
2         NaN         NaN  ...               NaN              NaN
3         NaN  CoCubes Id  ...  Graduation Marks  Graduation Year
4         NaN     2792845  ...               7.3             2020
5         NaN     2792847  ...               8.8             2020

[5 rows x 22 columns]

In [0]:
unplaced1.iloc[3][3]

'1210116101'

In [0]:
cocubes.tail()

      CoCubesId                   Name  ...  Software Engineer Software Tester
1762    2793778      Yetukuri Shivasai  ...      Need training   Need training
1763    2793547          R Rahul Varma  ...      Need training   Need training
1764    2794127            Vineeth Sai  ...      Need training   Need training
1765    2793877       Sunkari Maneesha  ...      Need training   Need training
1766    2793034  Makkena Bhargava Teja  ...      Need training   Need training

[5 rows x 26 columns]

In [0]:
unplaced.tail()

      Unnamed: 0 Unnamed: 1  ... Unnamed: 20 Unnamed: 21
1031         NaN    2879664  ...        6.55        2020
1032         NaN    2879665  ...           0        2020
1033         NaN    2879666  ...           0        2020
1034         NaN    2879667  ...           0        2020
1035         NaN    2879668  ...        7.46        2020

[5 rows x 22 columns]

In [0]:
cocubes2=cocubes

In [0]:
unplaced2=unplaced1

In [0]:
if(unplaced.iloc[3][3]==cocubes.iloc[1145][2]):
      cocubes.drop([j])
      print("kljd")
else:
  print("afafe")

afafe

In [0]:
for i in range(3,1036):
  for j in range(0,1767):
    if(unplaced.iloc[i][3]==cocubes.iloc[j][2]):
      cocubes2.drop([j])

KeyboardInterrupt: ignored

In [0]:
cocubes2.head()

   CoCubesId                          Name  ...  Software Engineer Software Tester
0    2793828                Rohith Narayan  ...         Good to go      Good to go
1    2793400              Sunkavalli Jnani  ...         Good to go      Good to go
2    2792958       Krishna Vivek Vinnakota  ...         Good to go      Good to go
3    2793375                      P Anusha  ...         Good to go      Good to go
4    2794244  Chilukala Sai Giridhar Reddy  ...         Good to go      Good to go

[5 rows x 26 columns]